import { findPackageManager } from "@license-auditor/package-manager-finder";
import { type LicenseStatus, checkLicenseStatus } from "./check-license-status";
import { extractPackageName, readPackageJson } from "./file-utils";
import { findLicense } from "./license-finder/find-license";

interface PackageInfo extends LicenseWithPath {
  package: string;
  path: string;
  status: LicenseStatus;
}

interface AuditSummary {
  allowed: number;
  disallowed: number;
  unknown: number;
}

interface LicenseAuditResult {
  resultMap: Map<string, PackageInfo>;
  summary: AuditSummary;
}

export async function auditLicenses(cwd: string): Promise<LicenseAuditResult> {
  const packageManager = await findPackageManager(cwd);
  console.log("Package Manager:", packageManager);

  const packagePaths: string[] = [];
  const resultMap = new Map<string, PackageInfo>();
  const summary: AuditSummary = {
    allowed: 0,
    disallowed: 0,
    unknown: 0,
  };

  for (const packagePath of packagePaths) {
    const packageName = extractPackageName(packagePath);

    if (resultMap.has(packageName)) {
      break;
    }
    const packageJson = readPackageJson(packagePath);

    const { license, licensePath } = findLicense(packageJson, packagePath);

    const status = checkLicenseStatus(license);

    const packageInfo: PackageInfo = {
      package: packageName,
      path: packagePath,
      license: license,
      licensePath: licensePath,
      status: status,
    };

    resultMap.set(packageName, packageInfo);
    summary[status] += 1;
  }

  return {
    resultMap,
    summary,
  };
}

// hardcoded for now
const packagePaths: string[] = [
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@biomejs/biome",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@cspotcode/source-map-support",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@eslint-community/eslint-utils",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@eslint-community/regexpp",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@eslint/config-array",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@eslint/core",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@eslint/eslintrc",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@eslint/js",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@eslint/object-schema",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@eslint/plugin-kit",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@humanwhocodes/module-importer",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@humanwhocodes/retry",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@jridgewell/resolve-uri",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@jridgewell/sourcemap-codec",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@jridgewell/trace-mapping",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@nodelib/fs.scandir",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@nodelib/fs.stat",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@nodelib/fs.walk",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@tsconfig/node10",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@tsconfig/node12",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@tsconfig/node14",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@tsconfig/node16",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@tsconfig/recommended",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@types/estree",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@types/json-schema",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@typescript-eslint/eslint-plugin",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@typescript-eslint/parser",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@typescript-eslint/scope-manager",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@typescript-eslint/type-utils",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@typescript-eslint/types",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@typescript-eslint/typescript-estree",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@typescript-eslint/utils",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@typescript-eslint/visitor-keys",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/acorn-jsx",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/acorn-walk",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/acorn",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/ajv",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/arg",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/brace-expansion",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/create-require",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/cross-spawn",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/cz-conventional-changelog",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/debug",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/deep-is",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/diff",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/dotenv",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/escape-string-regexp",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/eslint-config-turbo",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/eslint-plugin-only-warn",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/eslint-plugin-turbo",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/eslint-scope",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/eslint-visitor-keys",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/espree",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/esquery",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/esrecurse",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/estraverse",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/esutils",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/fast-glob",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/fast-json-stable-stringify",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/fast-levenshtein",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/fastq",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/file-entry-cache",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/find-up",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/flat-cache",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/flatted",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/glob-parent",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/globals",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/graphemer",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/husky",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/ignore",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/imurmurhash",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/is-path-inside",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/json-buffer",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/json-schema-traverse",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/json-stable-stringify-without-jsonify",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/keyv",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/levn",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/locate-path",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/make-error",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/merge2",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/minimatch",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/ms",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/natural-compare",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/optionator",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/p-limit",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/p-locate",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/path-exists",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/path-key",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/prelude-ls",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/punycode",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/queue-microtask",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/reusify",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/run-parallel",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/semver",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/shebang-command",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/shebang-regex",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/text-table",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/ts-api-utils",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/ts-node",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/turbo",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/type-check",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/typescript",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/uri-js",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/v8-compile-cache-lib",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/which",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/yn",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/yocto-queue",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/zod",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@biomejs/cli-darwin-arm64",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@eslint/config-array/node_modules/brace-expansion",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@eslint/config-array/node_modules/minimatch",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@eslint/eslintrc/node_modules/brace-expansion",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/import-fresh",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/js-yaml",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@eslint/eslintrc/node_modules/minimatch",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/strip-json-comments",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@total-typescript/ts-reset",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/is-glob",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/fast-deep-equal",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/balanced-match",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@commitlint/load",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/cz-conventional-changelog/node_modules/chalk",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/commitizen",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/conventional-commit-types",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/lodash.map",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/longest",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/word-wrap",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/eslint/node_modules/brace-expansion",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/chalk",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/eslint/node_modules/eslint-visitor-keys",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/jiti",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/lodash.merge",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/eslint/node_modules/minimatch",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/strip-ansi",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/espree/node_modules/eslint-visitor-keys",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/fast-glob/node_modules/glob-parent",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/micromatch",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@types/node",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/turbo-darwin-arm64",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/isexe",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/concat-map",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/parent-module",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/resolve-from",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/argparse",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/is-extglob",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@commitlint/config-validator",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@commitlint/execute-rule",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@commitlint/resolve-extends",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@commitlint/types",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@commitlint/load/node_modules/chalk",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/cosmiconfig-typescript-loader",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/cosmiconfig",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/lodash.isplainobject",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/lodash.uniq",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/cz-conventional-changelog/node_modules/ansi-styles",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/cz-conventional-changelog/node_modules/escape-string-regexp",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/cz-conventional-changelog/node_modules/supports-color",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/cachedir",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/dedent",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/detect-indent",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/find-node-modules",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/find-root",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/fs-extra",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/glob",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/inquirer",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/is-utf8",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/lodash",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/minimist",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/strip-bom",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/ansi-styles",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/supports-color",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/ansi-regex",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/braces",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/picomatch",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/undici-types",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/callsites",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@commitlint/config-validator/node_modules/ajv",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/global-directory",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/import-meta-resolve",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/lodash.mergewith",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@commitlint/resolve-extends/node_modules/resolve-from",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@types/conventional-commits-parser",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@commitlint/types/node_modules/chalk",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/env-paths",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/parse-json",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/cz-conventional-changelog/node_modules/color-convert",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/cz-conventional-changelog/node_modules/has-flag",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/findup-sync",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/merge",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/at-least-node",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/graceful-fs",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/jsonfile",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/universalify",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/fs.realpath",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/inflight",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/inherits",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/glob/node_modules/minimatch",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/once",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/path-is-absolute",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/ansi-escapes",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/cli-cursor",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/cli-width",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/external-editor",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/figures",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/mute-stream",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/ora",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/run-async",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/rxjs",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/string-width",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/through",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/wrap-ansi",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/color-convert",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/has-flag",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/fill-range",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/fast-uri",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@commitlint/config-validator/node_modules/json-schema-traverse",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/require-from-string",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/ini",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@babel/code-frame",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/error-ex",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/json-parse-even-better-errors",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/lines-and-columns",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/cz-conventional-changelog/node_modules/color-name",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/detect-file",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/resolve-dir",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/wrappy",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/glob/node_modules/brace-expansion",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/ansi-escapes/node_modules/type-fest",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/restore-cursor",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/chardet",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/iconv-lite",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/tmp",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/figures/node_modules/escape-string-regexp",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/bl",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/cli-spinners",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/is-interactive",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/is-unicode-supported",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/log-symbols",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/wcwidth",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/tslib",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/emoji-regex",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/is-fullwidth-code-point",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/color-name",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/to-regex-range",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@babel/highlight",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/picocolors",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/is-arrayish",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/expand-tilde",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/global-modules",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/onetime",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/signal-exit",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/safer-buffer",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/os-tmpdir",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/buffer",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/readable-stream",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/defaults",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/is-number",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@babel/helper-validator-identifier",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@babel/highlight/node_modules/chalk",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/js-tokens",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/homedir-polyfill",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/global-prefix",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/is-windows",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/mimic-fn",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/base64-js",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/ieee754",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/string_decoder",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/util-deprecate",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/clone",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@babel/highlight/node_modules/ansi-styles",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@babel/highlight/node_modules/escape-string-regexp",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@babel/highlight/node_modules/supports-color",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/parse-passwd",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/global-prefix/node_modules/ini",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/global-prefix/node_modules/which",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/safe-buffer",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@babel/highlight/node_modules/color-name]",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@babel/highlight/node_modules/color-convert",
  "/Users/angelikajeziorska/Documents/projects/license-auditor/node_modules/@babel/highlight/node_modules/has-flag",
];

export async function go(): Promise<void> {
  const auditResult = await auditLicenses(
    "/Users/angelikajeziorska/Documents/projects/license-auditor",
  );

  console.log("Result Map:", auditResult.resultMap);
  console.log("Summary:", auditResult.summary);
}

go();
