name: Push to master branch
on:
  push:
    branches:
      - master
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: yarn
      - name: Run static code analysis
        run: yarn run lint
      - name: Run tests
        run: yarn test
